import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Navbar } from "./components/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
     <Navbar />
        {children}
      </body>
    </html>
  );
}
